// Builds a single-transaction "Payment Receipt" HTML document.
//
// It is shown in-app inside a WebView and can be exported on demand to a PDF via
// expo-print. The receipt is intentionally TEMPORARY: it is generated fresh each
// time the user opens a transaction and is not stored anywhere, so once the viewer
// is dismissed that individual PDF is no longer accessible from the app. (The full
// transaction history lives in the separate Account Statement PDF.)
//
// Text is in English to match the other new features.

import { DS_LOGO } from "./dsLogo";

const round2 = (n) => Math.round((Number(n) || 0) * 100) / 100;
const money = (n) => round2(n).toFixed(2) + " EUR";

const esc = (s) =>
  String(s == null ? "" : s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

const pad = (n) => (n < 10 ? "0" + n : "" + n);
const fmtDateTime = (d) =>
  `${pad(d.getDate())}.${pad(d.getMonth() + 1)}.${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`;

// e.g. 42 -> "DSB-00000042"
const fmtTxId = (id) => "DSB-" + String(id == null ? "" : id).padStart(8, "0");

export function buildReceiptHtml({ user, tx }) {
  const isUserSender = tx.sender_name === user.name && tx.sender_surname === user.surname;

  const amount = parseFloat(tx.amount) || 0;
  const sent = isUserSender;
  const counterparty = sent
    ? `${tx.receiver_name || ""} ${tx.receiver_surname || ""}`.trim()
    : `${tx.sender_name || ""} ${tx.sender_surname || ""}`.trim();
  const holder = `${user.name || ""} ${user.surname || ""}`.trim() || "—";

  const date = new Date(tx.created_at);
  const dateStr = isNaN(date.getTime()) ? "—" : fmtDateTime(date);

  const fromName = sent ? holder : counterparty || "—";
  const toName = sent ? counterparty || "—" : holder;

  const row = (label, value, cls = "") =>
    `<div class="row"><div class="lab">${esc(label)}</div><div class="val ${cls}">${esc(value)}</div></div>`;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<style>
  * { box-sizing: border-box; -webkit-text-size-adjust: 100%; }
  body { margin: 0; background: #eef1f5; color: #1f2937; font-family: Helvetica, Arial, sans-serif; font-size: 13px; }
  .sheet { max-width: 520px; margin: 0 auto; background: #fff; padding: 24px 22px 26px; }
  .top { display: flex; justify-content: space-between; align-items: center; }
  .logo { display: flex; align-items: center; gap: 8px; }
  .logo-img { width: 38px; height: 38px; object-fit: contain; }
  .logo-name { font-size: 16px; font-weight: 800; color: #191970; }
  .status { font-size: 11px; font-weight: 800; letter-spacing: 0.5px; color: #1f8a4c; background: #e7f6ec; padding: 6px 12px; border-radius: 20px; text-transform: uppercase; }
  .rule { height: 2px; background: #191970; margin: 16px 0 18px; border-radius: 2px; }
  .hero { text-align: center; padding: 8px 0 18px; }
  .hero .cap { font-size: 11px; letter-spacing: 1px; text-transform: uppercase; color: #98a0ad; }
  .hero .amt { font-size: 34px; font-weight: 800; margin-top: 6px; color: #191970; }
  .hero .amt.sent { color: #1f2937; }
  .hero .amt.recv { color: #1f8a4c; }
  .hero .dir { font-size: 12px; color: #6b7280; margin-top: 4px; }
  .rows { border: 1px solid #e6e9ef; border-radius: 12px; overflow: hidden; margin-top: 4px; }
  .row { display: flex; justify-content: space-between; gap: 14px; padding: 13px 14px; border-bottom: 1px solid #eef0f3; }
  .row:last-child { border-bottom: none; }
  .row:nth-child(even) { background: #f8f9fb; }
  .lab { font-size: 12px; color: #98a0ad; }
  .val { font-size: 13px; font-weight: 700; color: #1f2937; text-align: right; }
  .val.mono { font-family: "Courier New", monospace; letter-spacing: 0.5px; }
  .footer { margin-top: 20px; border-top: 1px solid #e6e9ef; padding-top: 12px; font-size: 10px; color: #aab1bd; line-height: 1.5; text-align: center; }
</style>
</head>
<body>
  <div class="sheet">
    <div class="top">
      <div class="logo">
        <img class="logo-img" src="${DS_LOGO}" alt="DS Banking" />
        <div class="logo-name">DS&nbsp;Banking</div>
      </div>
      <div class="status">Completed</div>
    </div>
    <div class="rule"></div>

    <div class="hero">
      <div class="cap">Payment Receipt</div>
      <div class="amt ${sent ? "sent" : "recv"}">${(sent ? "- " : "+ ") + money(amount)}</div>
      <div class="dir">${sent ? "Money Sent" : "Money Received"}</div>
    </div>

    <div class="rows">
      ${row("Transaction ID", fmtTxId(tx.id), "mono")}
      ${row("Date & Time", dateStr)}
      ${row("From", fromName)}
      ${row("To", toName)}
      ${row("Amount", money(amount))}
      ${tx.description ? row("Note", tx.description) : ""}
      ${row("Status", "Completed")}
    </div>

    <div class="footer">
      This receipt was generated by DS Banking for a single transaction. Amounts are shown in EUR.
      A full list of your transactions is available in your Account Statement.
    </div>
  </div>
</body>
</html>`;
}
